### ISSUE TITLE
连续桢发送问题

### ISSUE THREAD

**Issue by wwwying9** [SummerFalls/UDS_S32K144_Bootloader#1]
你好，使用这个boot的时候，我用CAN上位机发送02 27 01 报文，请求种子，这时应该收到一串大于8字节的数据，单片机应该分成几桢数据发给我。但是上位机只显示收到了回复的首桢数据（10 12 67 01 1C 02 DE 17）， 后续桢的数据就没收到了，能否帮忙分析大概哪出了问题么？

**Comment by zangege** [comment]
> 你好，使用这个boot的时候，我用CAN上位机发送02 27 01 报文，请求种子，这时应该收到一串大于8字节的数据，单片机应该分成几桢数据发给我。但是上位机只显示收到了回复的首桢数据（10 12 67 01 1C 02 DE 17）， 后续桢的数据就没收到了，能否帮忙分析大概哪出了问题么？

你看下UDS诊断协议吧，多帧回复时需要上位机发送流控帧
