### ISSUE TITLE
可以一起参与bootloader的维护和开发吗？

### ISSUE THREAD

**Issue by xinkunlong** [SummerFalls/UDS_S32K144_Bootloader#2]
我在原有的基础上添加了 发送填充功能，但是我不知道如何提进提交和提交的格式

**Comment by SummerFalls** [comment]
> 我在原有的基础上添加了 发送填充功能，但是我不知道如何提进提交和提交的格式

你好，请问你的刷新测试环境是什么？CANOE还是其它几家厂商？如果附上截图会更好。因为目前我只测试了周立功的上位机ECU刷新功能，不清楚Bootloader与其它CAN仪器厂商的上位机是否兼容，所以需要你提供对应的使用环境以供参考。

至于提交，当你Fork本仓库到你的账号下之后，在您本地电脑上安装好Git SCM之后用VSCode内的版本管理工具进行clone到您电脑本地，在进行相应的代码更改后先执行Local commit，然后再push到你的远程仓库，之后你就可以在你的远程仓库页面上发起pull request了，我会review你的代码进行跟进。

提交的格式你先按照你的尝试一次，之后我会再根据具体情况规范一下。因为也是第一次有人给我这里尝试发送PR

**Comment by xinkunlong** [comment]
bootlaoder 上位机是根据python进行单独开发，目前的硬件是PCAN，等升级流程完善后，打算兼容所有的硬件进行程序的刷新，
然后发现了这个bootloader程序有很多不符合IS014229-1的地方，
所以想调整一下

**Comment by xinkunlong** [comment]
我想调整一下，成为更加通用的bootloader程序，不仅仅是支持周立功的上位机ECU刷新功能

**Comment by SummerFalls** [comment]
我同样想兼容更多的CAN盒厂商，只是受限于资金，只对周立功做了测试支持。另外的确有部分不符合ISO 14229-1，如果你有做相应调整，可以在你 Fork 之后创建新的分支进行修改，之后再 Pull Request，我可以参与 Review 👍
